#!/bin/sh
set -e

echo "Building environment..."
virtualenv --python=python3 /var/recall/environment/
. /var/recall/environment/bin/activate
pip install /usr/share/recall/bundle.zip
deactivate
echo "...done"
echo "Now rename /etc/recall.config.sh.example to /etc/recall.config.sh"