#!/bin/sh
set -e

echo "Building environement..."
virtualenv --python=python2 /var/recall/environment/
. /var/recall/environment/bin/activate
pip install /usr/share/recall/bundle.zip
deactivate
echo "...done"

