#!/usr/bin/env bash
set -e
set -x

OPS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_DIR=$OPS_DIR/build.d
PROJECT_ROOT=$OPS_DIR/..
ALTAR_ROOT=$PROJECT_ROOT/../altar

create_build_directory () {
    if [[ -d $BUILD_DIR ]]
    then
	rm -rf $BUILD_DIR
    fi
    cp -Rv $OPS_DIR/debian/ $BUILD_DIR
}

set_version () {
    if [ $BUILD_NUMBER ]
    then
	VERSION=$BUILD_NUMBER
    else
	VERSION=0-DEV
    fi
    sed -i "s/0-UNKNOWN/${VERSION}/" $OPS_DIR/build.d/DEBIAN/control
}

build_bootstrap_if_needed () {
    if [[ ! -f $PROJECT_ROOT/www/third-party/bootstrap/css/bootstrap.css ]]
    then
	BOOTSTRAP_DIR=$PROJECT_ROOT/www/third-party/bootstrap/
	mkdir $BOOTSTRAP_DIR/css
	lessc $BOOTSTRAP_DIR/less/bootstrap.less > $BOOTSTRAP_DIR/css/bootstrap.css
	lessc $BOOTSTRAP_DIR/less/responsive.less > $BOOTSTRAP_DIR/css/bootstrap-responsive.css
    fi
}

insert_web_resources () {
    build_bootstrap_if_needed
    cp -R $PROJECT_ROOT/www $BUILD_DIR/usr/share/recall/www/
    echo $VERSION > $BUILD_DIR/usr/share/recall/www/version
}

insert_python_resources () {
    cp -R $PROJECT_ROOT/src $BUILD_DIR/usr/share/recall/
}

insert_python_bundle () {
    if [[ ! -f $OPS_DIR/artefacts/requirements.md5 ]]
    then
	touch $OPS_DIR/artefacts/requirements.md5
    fi
    EXPECTED=`md5sum $PROJECT_ROOT/requirements`
    SUM=`cat $OPS_DIR/artefacts/requirements.md5`
    if [[ $EXPECTED != $SUM ]]
    then
	pip bundle $BUILD_DIR/usr/share/recall/bundle.zip -r $PROJECT_ROOT/requirements
	cp $BUILD_DIR/usr/share/recall/bundle.zip $OPS_DIR/artefacts/bundle.zip
	md5sum $PROJECT_ROOT/requirements > $OPS_DIR/artefacts/requirements.md5
    else
	echo "REUSING OLD BUNDLE"
	cp $OPS_DIR/artefacts/bundle.zip $BUILD_DIR/usr/share/recall/bundle.zip
    fi
}

move_config_file () {
    mv $BUILD_DIR/usr/share/recall/www/config.js $BUILD_DIR/etc/recall/config.js
}
    
clean_out_temporary_files () {
    find $OPS_DIR/debian/ -name '*~' -exec rm '{}' ';'
}

insert_documentation () {
    cp $PROJECT_ROOT/LICENCE $BUILD_DIR/usr/share/doc/recall/copyright
    # touch $BUILD_DIR/usr/share/doc/recall/changelog.Debian
    # gzip --best $BUILD_DIR/usr/share/doc/recall/changelog.Debian
}

remove_gitignores () {
    rm `find $BUILD_DIR -name '*gitignore*'`
}

build_artefact () {
    if [[ ! $BUILD_NUMBER ]]
    then
	PREVIOUS_DEV_BUILD=$OPS_DIR/artefacts/recall_0-DEV_all.deb
	if [[ -f $PREVIOUS_DEV_BUILD ]]
	then
	    rm $PREVIOUS_DEV_BUILD
	fi
    fi
    fakeroot dpkg-deb --build $BUILD_DIR $OPS_DIR/artefacts/recall.deb
    dpkg-name $OPS_DIR/artefacts/recall.deb
}

push_tags_if_on_ci () {
    if [[ $BUILD_NUMBER ]]
    then
	git push --tags
    fi
}

create_build_directory
set_version
insert_web_resources
insert_python_resources
insert_python_bundle
move_config_file
insert_documentation
clean_out_temporary_files
remove_gitignores
build_artefact
push_tags_if_on_ci