#!/usr/bin/env python

PYMONGO_EXPECTED_MAJOR_VERSION = 2
PYMONGO_EXPECTED_MINOR_VERSION = 1
MONGODB_EXPECTED_PORT = 27017
MONGODB_EXPECTED_HOST = "localhost"
PYTHON_EXPECTED_MAJOR_VERSION = 2
PYTHON_EXPECTED_MINOR_VERSION = 7

import sys
import os

def exit_1_with_message(message):
    print "FAILURE: " + message
    exit(1)

def assert_presence_of_binary_on_path(name):
    exit_value = os.system("which " + name + ">> /dev/null")
    assert exit_value == 0

def assert_presence_of_file(path):
    assert os.path.isfile(path)

def main():

    try:
        assert_presence_of_file("/usr/sbin/nginx")
    except AssertionError:
        exit_1_with_message(
            "Need nginx - install nginx-light")

    try:
        assert_presence_of_binary_on_path("lessc")
        assert_presence_of_binary_on_path("uglifyjs")
    except AssertionError:
        exit_1_with_message(
            "Need to install lessc and uglifyjs.  There aren't normally\n" +
            "distro packages, you will have to install nodejs, and then:\n" +
            "do `npm install less`, `npm install uglify-js`.  Then you'll\n" +
            "have to put them on your $PATH.  I know this sucks.")

    try:
        assert_presence_of_binary_on_path("lintian")
    except AssertionError:
        exit_1_with_message(
            "Need to install debian's lintian package")

    try:
        assert sys.version_info >= (
            PYTHON_EXPECTED_MAJOR_VERSION,
            PYTHON_EXPECTED_MINOR_VERSION)
    except AssertionError:
        exit_1_with_message(
            "Need python 2.7 or greater")

    try:
        import pymongo
        assert pymongo.version_tuple[0] == PYMONGO_EXPECTED_MAJOR_VERSION
        assert pymongo.version_tuple[1] == PYMONGO_EXPECTED_MINOR_VERSION
    except ImportError:
        exit_1_with_message(
            "Need to install pymongo - try the debian package python-pymongo")
    except AssertionError and AttributeError:
        exit_1_with_message(
            "Your pymongo version is %s but recall expects %s.%s.*" % (
                pymongo.version,
                PYMONGO_EXPECTED_MAJOR_VERSION,
                PYMONGO_EXPECTED_MINOR_VERSION))

    try:
        pymongo.Connection(MONGODB_EXPECTED_HOST, MONGODB_EXPECTED_PORT)
    except:
        exit_1_with_message(
            "Unable to start test connection with mongodb." +
            "  Is it running on %s:%s ?" % (
                MONGODB_EXPECTED_HOST,
                MONGODB_EXPECTED_PORT))

    try:
        import bcrypt
    except ImportError:
        exit_1_with_message(
            "Need to install bcrypt - try the debian package python-bcrypt")

    try:
        import flask
    except ImportError:
        exit_1_with_message(
                "Need to install flask - try the debian package python-flask")

    try:
        import requests
    except ImportError:
        exit_1_with_message(
            "Need to install requests - try the debian package python-requests")

    print "All dependencies installed and database up"

if __name__ == "__main__":
    main()
