#!/usr/bin/env bash
set -e
set -x

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/..

# SCP the binary onto the machine
scp -Bv $PROJECT_ROOT/ops/artefacts/recall_${VERSION}_all.deb ubuntu@middle.calpaterson.com:/home/ubuntu/

# SSH install and restart the service
ssh ubuntu@middle.calpaterson.com "sudo dpkg -i recall_${VERSION}_all.deb"
ssh ubuntu@middle.calpaterson.com "sudo supervisorctl restart recall-server"
ssh ubuntu@middle.calpaterson.com "supervisorctl restart recall-worker"

