#!/usr/bin/env bash

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/..

export RECALL_ELASTICSEARCH_HOST=localhost
export RECALL_ELASTICSEARCH_PORT=9200
export RECALL_MONGODB_DB_NAME=test
export RECALL_MONGODB_DB_HOST=localhost
export RECALL_MONGODB_DB_PORT=27017
export RECALL_PASSWORD_SALT='$2a$04$HDPphuN9nmnFLPxt.fWQ3e'
export RECALL_REDIS_SERVER_HOST=localhost
export RECALL_REDIS_SERVER_NUMBER=15
export RECALL_REDIS_SERVER_PORT=6379
export RECALL_SERVER_HOST=localhost
export RECALL_SERVER_PORT=5003

python ${PROJECT_ROOT}/server/server.py >> /dev/null 2>&1 &
python ${PROJECT_ROOT}/worker/worker.py >> /dev/null 2>&1 &

# This is required on slow machines in order to allow the above to get
# started
sleep 0.1

python -m unittest discover -s $PROJECT_ROOT -v

killall -9 python

if [[ WORKER_TESTS != 0 || SERVER_TESTS != 0 ]]
then
    exit 1
fi