#!/usr/bin/env bash
set -e

trap 'kill 0' SIGINT SIGTERM EXIT

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/..

export RECALL_API_BASE_URL='http://localhost:6000'
export RECALL_API_HOST="localhost"
export RECALL_API_PORT=6000
export RECALL_ELASTICSEARCH_HOST=localhost
export RECALL_ELASTICSEARCH_PORT=9200
export RECALL_ELASTICSEARCH_INDEX=test
export RECALL_MONGODB_DB_NAME=test
export RECALL_MONGODB_HOST=localhost
export RECALL_MONGODB_PORT=27017
export RECALL_PASSWORD_SALT='$2a$04$HDPphuN9nmnFLPxt.fWQ3e'
export RECALL_REDIS_HOST=localhost
export RECALL_REDIS_DB=15
export RECALL_REDIS_PORT=6379
export RECALL_DEBUG_MODE=true

python -3 ${PROJECT_ROOT}/server/server.py &
python -3 ${PROJECT_ROOT}/worker/worker.py &

python -m unittest discover -s $PROJECT_ROOT -v